
# DATASOURCE
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8080
# JPA / HIBERNATE
# ===============================
# CAMBIO: Si usas schema.sql manual, ponlo en 'none' o 'validate'. 
# Si quieres que Hibernate cree la tabla según tus clases @Entity, déjalo en 'update'.
spring.jpa.hibernate.ddl-auto=update

# CAMBIO: El dialecto MySQL8Dialect está deprecado en versiones nuevas, mejor usa el genérico:
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true


# ===============================
# SQL INIT (Vital para que funcione data.sql)
# ===============================
spring.sql.init.mode=always

# Esto asegura que data.sql corra DESPUÉS de que Hibernate cree las tablas
spring.jpa.defer-datasource-initialization=true

# Opcional: Spring ya los busca por defecto si se llaman así, pero dejarlos no hace daño
#spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

