name: CI - Feature Pipeline

on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - main
      - develop

jobs:
  call-reusable-build:
    uses: ./.github/workflows/build-reusable.yml